spring.application.name=restdb
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres?user=postgres.brnlbgapdarqtyaxwdnd&password=Vitornerf1#
spring.datasource.plattform=postgres
spring.jpa.hibernate.ddl-auto=create #toda classe que tiver o @Entity, ele vai criar uma tabela no postgres